# Generated by Django 3.1 on 2021-05-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_name', models.CharField(max_length=200)),
                ('crypto_symbol', models.CharField(max_length=10)),
                ('last_traded_value', models.FloatField()),
                ('Day_low', models.FloatField()),
                ('Day_high', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Cryptos',
            },
        ),
        migrations.CreateModel(
            name='KeyFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('bought_at', models.FloatField()),
                ('market', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='currencies.cryptomodel')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
